# Generated by Django 4.2.6 on 2023-11-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
